---
extends:
  - stylelint-config-standard
  - stylelint-config-property-sort-order-smacss

ignoreFiles:
  - node_modules/**/*
  - dist/**/*

plugins:
  - stylelint-selector-bem-pattern
  - stylelint-scss
  - stylelint-order

rules:
  font-family-name-quotes: always-where-recommended
  function-url-quotes: always
  selector-attribute-quotes: always
  string-quotes: single

  at-rule-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  selector-no-vendor-prefix: true
  value-no-vendor-prefix: true

  max-nesting-depth: 3
  selector-max-compound-selectors: 4
  selector-max-specificity: 0,4,1

  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - at-root
      - content
      - each
      - else
      - error
      - for
      - function
      - include
      - if
      - mixin
      - return
      - warn
  at-rule-blacklist:
    - extend

  property-no-unknown:
    - true
    - ignoreProperties:
      - contain

  selector-max-id: 0
  selector-no-qualifying-type: true
  selector-max-type:
    - 0
    - ignoreTypes:
      - /fieldset/
  selector-max-universal: 0

  font-weight-notation: named-where-possible
  function-url-no-scheme-relative: true

  plugin/selector-bem-pattern:
    componentName: ^[a-z]+(?:-[a-z]+)*$
    componentSelectors: ^{componentName}(?:__[a-z]+(?:-[a-z]+)*)*(?:--[a-z]+(?:-[a-z]+)*)*(?:\[.+\])*$

  scss/selector-no-redundant-nesting-selector: true
  scss/at-import-no-partial-leading-underscore: true
  scss/at-else-closing-brace-newline-after: always-last-in-chain
  scss/at-else-closing-brace-space-after: always-intermediate
  scss/at-else-empty-line-before: never
  scss/at-if-closing-brace-newline-after: always-last-in-chain
  scss/at-if-closing-brace-space-after: always-intermediate
